# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5f2f23cb26b968d3f18c9322df0ef5faedb80a3a895c1f32be07f705154537efc3b7059179319f682a4da8c4f081c2a7b2d84f1c108ea40b1b6c48fd0eb62f7

test:
  secret_key_base: e1c90a1b4b52797aa22a9f4f2fe62fd4db99b9c01f98016460dc1af8eb0c4fa82ddb4297b42a4e80f120c55389884281f05def12ec88f988e84a92e6ed7fa24f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
